#!/bin/sh
module="sue_donimous"
device="sue_donimous"
mode="666"

# Group: since distributions do it differently, look for wheel or use staff
if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi

# invoke insmod with all arguments we got
# and use a pathname, as newer modutils don't look in . by default
insmod ./$module.ko $* || exit 1

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's simple that has several devices in it.

rm -f /dev/${device}_*
mknod /dev/${device}_rx0 c $major 0
mknod /dev/${device}_tx0 c $major 1
mknod /dev/${device}_rx1 c $major 2
mknod /dev/${device}_tx1 c $major 3
chgrp $group /dev/${device}_*
chmod $mode  /dev/${device}_*
